name: Bug Report
description: Having trouble browsing the web? Please report it here.
title: "[Bug] "
labels: ["bug"]
assignees:
  - LittleChest
body:
  - type: markdown
    attributes:
      value: |
        We're sorry that you're having trouble browsing this page, please fill out this form completely so we can investigate the issue.
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Opera
        - Other (Please fill in "Extra information")
    validations:
      required: true
  - type: input
    id: path
    attributes:
      label: URL path
      description: Please copy the URL you are visiting here.
      placeholder: eg. https://leavesmc.top/downloads/leaves
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: expect-to-happen
    attributes:
      label: What did you expect to happen?
      placeholder: Tell us what you think!
    validations:
      required: true
  - type: textarea
    id: reproduce-operation
    attributes:
      label: Reproduce operation
      value: "1. "
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Console log
      description: Please open the developer tools and switch to the console and paste the output here. You can also paste a screenshot if the output is too much.
      render: shell
  - type: textarea
    id: extra-information
    attributes:
      label: Extra information
      placeholder: Is there any additional information that needs to be added?
